---
title: "Other dataset"
author: "Gabrielle Ruehle"
date: "9/29/2021"
output: html_document
---

```{r}
#read in 763K App Info Data
library(readr)
app_info <- read_csv("~/CDC2021/archive/763K_plus_IOS_Apps_Info.csv")
head(app_info)
```

```{r}
#histograms of Price (USD) of all apps in dataset
hist(app_info$Price_USD)
hist(app_info$Price_USD[app_info$Price_USD <= 20 & app_info$Price_USD > 0])
```
```{r}
#make original release date into a Year Month variable
library(dplyr)
library(zoo)
app_info <- app_info %>% mutate(Month_Year = zoo::as.yearmon(Original_Release_Date)) 
```
```{r}
#create a data table with the number of apps and average price of apps released by month/year
month_year_info <- app_info %>%
  group_by(Month_Year) %>%
  summarise(count = n(), avg_price = mean(Price_USD, na.rm=T))
```

```{r}
library(ggplot2)
library(scales)
library(zoo)

#line graph of average price of apps over time
ggplot(data = month_year_info, aes(Month_Year, avg_price)) +
  geom_line(color = '#021092', size = 2) +
  theme_minimal() +
  labs(title = "Average App Price by Month over Time", 
       x = "Year",
       y = "Average Price (USD)")+
  scale_x_yearmon(format = "%Y")

#line graph of number of apps released over time
ggplot(data = month_year_info, aes(Month_Year, count)) +
  geom_line(color = '#021092', size = 2) +
  theme_minimal() +
  labs(title = "Number of Apps Released by Month over Time", 
       x = "Year",
       y = "Number of Apps Released")+
  scale_x_yearmon(format = "%Y")
```

